name: Deploy Slides to Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: 'package.json'
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install dependencies
        run: pnpm install
      - name: Build all presentations
        run: pnpm -r build
      - name: Export all presentations to PDF
        run: pnpm -r export
      - name: Create dist directory
        run: |
          rm -rf dist
          mkdir -p dist
      - name: Aggregate presentation builds and PDFs
        run: |
          for presentation in slides/*/; do
            presentation_name=$(basename "$presentation")
            if [ -d "$presentation/dist" ]; then
              mkdir -p "dist/$presentation_name"
              cp -r "$presentation/dist/"* "dist/$presentation_name/"
              echo "✅ Copied $presentation_name build to dist/$presentation_name"

              # Copy PDF if it exists
              if [ -f "$presentation/slides-export.pdf" ]; then
                cp "$presentation/slides-export.pdf" "dist/$presentation_name.pdf"
                echo "✅ Copied $presentation_name PDF to dist/$presentation_name.pdf"
              fi
            else
              echo "⚠️  No dist folder found for $presentation_name"
            fi
          done
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
